WSL tweaks

diff --git a/roles/supervisord/templates/init-script.j2 b/roles/supervisord/templates/init-script.j2
--- a/roles/supervisord/templates/init-script.j2
+++ b/roles/supervisord/templates/init-script.j2
@@ -33,6 +33,7 @@ if [ -f {{ brew_install_path }}/etc/default/supervisor ] ; then
 fi
 
 DAEMON_OPTS="-c {{ brew_install_path }}/etc/supervisord.conf $DAEMON_OPTS"
+DAEMON_OPTS_SUPERVISORD="-j $PIDFILE $DAEMON_OPTS"
 
 set -e
 
@@ -53,10 +54,16 @@ running()
 # (works for all users)
 
     # No pidfile, probably no daemon present
-    [ ! -f "$PIDFILE" ] && return 1
+    [ ! -f "$PIDFILE" ] && {
+        echo "\nPid file not found: $PIDFILE\n"
+        return 1
+    }
     # Obtain the pid and check it against the binary name
     pid=`cat $PIDFILE`
-    running_pid $pid $DAEMON || return 1
+    running_pid $pid $DAEMON || {
+        echo "\DAEMON ($DAEMON) with pid=$pid not running\n"
+        return 1
+    }
     return 0
 }
 
@@ -84,7 +91,7 @@ case "$1" in
   start)
 	echo -n "Starting $DESC: "
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--startas $DAEMON -- $DAEMON_OPTS
+		--startas $DAEMON -- $DAEMON_OPTS_SUPERVISORD
 	test -f $PIDFILE || sleep 1
         if running ; then
             echo "$NAME."
@@ -125,7 +132,7 @@ case "$1" in
 	#	just the same as "restart" except that it does nothing if the
 	#   daemon isn't already running.
 	# check wether $DAEMON is running. If so, restart
-	start-stop-daemon --stop --test --quiet --pidfile $PIDFILE \
+    start-stop-daemon --stop --test --quiet --pidfile $PIDFILE \
         --startas $DAEMON \
 	&& $0 restart \
 	|| exit 0
@@ -135,7 +142,7 @@ case "$1" in
     start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
 	[ -n "$DODTIME" ] && sleep $DODTIME
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-		--startas $DAEMON -- $DAEMON_OPTS
+		--startas $DAEMON -- $DAEMON_OPTS_SUPERVISORD
 	echo "$NAME."
 	;;
   status)
