update hostnames

diff --git a/roles/nginx-php-fpm/templates/hostnames.j2 b/roles/nginx-php-fpm/templates/hostnames.j2
--- a/roles/nginx-php-fpm/templates/hostnames.j2
+++ b/roles/nginx-php-fpm/templates/hostnames.j2
@@ -9,22 +9,48 @@ function usage {
 
 if [[ -z $2 ]]; then
   usage
-else 
+else
   export HOSTNAME=$2;
 fi
 
-if ! [[ $2 =~ "[a-z0-9_\-]+\.[a-z0-9_\-]+$" ]]; then
-  echo "Hostname must contain 1st and 2nd levels"
+if ! [[ $2 =~ [a-z0-9_\-]+\.[a-z0-9_\-]+$ ]]; then
+
+  echo "Invalid hostname '$2', hostname must contain 1st and 2nd levels"
   exit 1
 fi
 
 if [[ -z $3 ]]; then
-  export PROJECT_NAME=$(echo $1 | awk -F. '{print $1}')
+  export PROJECT_NAME=$(echo $2 | awk -F. '{print $1}')
 fi
 
 if [[ -z $4 ]]; then
-  export POOL_NAME=$(echo $1 | awk -F. '{ for (i=NF-2;i>0;i--){ printf "%s", $(NF-i) "." }; printf "%s", $(NF)}')
+  export POOL_NAME=$(echo $2 | awk -F. '{ for (i=NF-2;i>0;i--){ printf "%s", $(NF-i) "." }; printf "%s", $(NF)}')
 fi
+
+function add_hostname {
+  echo "Creating webserver record for $1 hostname"
+
+  crtgen "${HOSTNAME}"
+
+  if [[ -f "/usr/local/etc/nginx/servers_custom/${HOSTNAME}.conf" ]]; then
+    echo "Hostname already exists";
+    exit 0
+  fi
+
+  gomplate -f "/usr/local/etc/nginx/custom_server.conf.tpl" --left-delim '<?' --right-delim '?>' -o "/usr/local/etc/nginx/servers_custom/${HOSTNAME}.conf"
+
+  echo "Restarting nginx..."
+  supervisorctl restart nginx
+}
+
+function remove_hostname {
+  echo "Creating webserver record for $1 hostname"
+
+  rm "/usr/local/etc/nginx/servers_custom/${HOSTNAME}.conf"
+
+  echo "Restarting nginx..."
+  supervisorctl restart nginx
+}
 
 case "$1" in
 "add")
@@ -37,27 +63,3 @@ case "$1" in
     usage
     ;;
 esac
-
-function add_hostname {
-  echo "Creating webserver record for $1 hostname"
-  
-  crtgen "${HOSTNAME}"
-  
-  if [[ -f "{{ homebrew_install_path }}/etc/nginx/servers_custom/${HOSTNAME}.conf" ]]; then
-    echo "Hostname already exists";
-    exit 0
-  fi
-  
-  gomplate -f "{{ homebrew_install_path }}/etc/nginx/custom_server.conf.tpl" --left-delim '<?' --right-delim '?>' -o "{{ homebrew_install_path }}/etc/nginx/servers_custom/${HOSTNAME}.conf"
-  
-  echo "Restarting nginx..."
-  supervisorctl restart nginx
-}
-
-function remove_hostname {
-  echo "Creating webserver record for $1 hostname"
-  
-  rm "{{ homebrew_install_path }}/etc/nginx/servers_custom/${HOSTNAME}.conf"
-  
-  echo "Please restart nginx"
-}
